// component/portfolio/comments/strings.ts
export const STRINGS = {
  es: {
    title: { normal: "COMENTARIOS", hacker: "GUESTBOOK.log" },
    subtitle: { normal: "Dejame tu mensaje", hacker: "// Firma el repo humano" },
    name: "Nombre",
    role: "Rol (opcional)",
    rolePh: "Frontend, Tech Lead, Cliente, etc.",
    namePh: "Marcos",
    msg: "Mensaje",
    msgPhNormal: "Estoy deseando contratarte",
    msgPhHacker: 'echo "Gran trabajo, shippeamos en tiempo récord" >> guestbook',
    chars: "caracteres",
    instant: "Se publicará al instante",
    send: "Enviar",
    empty: "Aún no hay mensajes. ¡Sé el primero en firmar!",
    more: "Ver más",
    less: "Ver menos",
  },
  en: {
    title: { normal: "COMMENTS", hacker: "GUESTBOOK.log" },
    subtitle: { normal: "Leave me your message", hacker: "// Sign the human repo" },
    name: "Name",
    role: "Role (optional)",
    rolePh: "Frontend, Tech Lead, Client, etc.",
    namePh: "John",
    msg: "Message",
    msgPhNormal: "I'm looking forward to hiring you",
    msgPhHacker: 'echo "Great job, shipped in record time" >> guestbook',
    chars: "characters",
    instant: "Will be published instantly",
    send: "Send",
    empty: "No messages yet. Be the first to sign!",
    more: "Show more",
    less: "Show less",
  },
} as const;
